name = "api-tester"
compatibility_date = "2024-03-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
watch_dir = "src"

[env.production]
routes = [
  { pattern = "/*", zone_name = "api-tester.pages.dev" }
]

[site]
bucket = ".vercel/output/static"
entry-point = ".vercel/output/functions/_worker.js" 